### ISSUE TITLE
Error: no such target '//:java/com/google/security/wycheproof/testcases/SpongyCastleTest': 

### ISSUE THREAD

**Issue by sunipa21** [google/wycheproof#11]
Hi,

I am trying to setup **wycheproof** on windows 8 machine and getting below mentioned error:

**ERROR: no such target '//:java/com/google/security/wycheproof/testcases/SpongyCastleTest': 
target 'java/com/google/security/wycheproof/testcases/SpongyCastleTest' not declared in package '' defined by C:/Softy/wycheproof-master/wycheproof-master/BUILD.
INFO: Elapsed time: 0.707s
ERROR: Couldn't start the build. Unable to run tests.**

Note: 
1. Tried navigating inside "\wycheproof-master\wycheproof-master\java\com\google\security\wycheproof>" but still not resolved
2. Tried building bazel and got stuck with below data:
**$ bash C:/Users/west/Downloads/bazel-0.4.3/bazel-0.4.3/compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    C:/Users/west/Downloads/bazel-0.4.3/bazel-0.4.3/compile.sh compile /pat                          h/to/bazel
🍃  Building Bazel from scratch
ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact

--------------------------------------------------------------------------------
NOTE: This failure is likely occuring if you are trying to bootstrap bazel from
a developer checkout. Those checkouts do not include the generated output of
the protoc compiler (as we prefer not to version generated files).

* To build a developer version of bazel, do

    bazel build //src:bazel

* To bootstrap your first bazel binary, please download a dist archive from our
  release page at https://github.com/bazelbuild/bazel/releases and run
  compile.sh on the unpacked archive.

The full install instructions to install a release version of bazel can be found
at https://bazel.build/versions/master/docs/install.html#compiling-from-source
For a rationale, why the bootstrap process is organized in this way, see
https://bazel.build/designs/2016/10/11/distribution-artifact.html
--------------------------------------------------------------------------------**
3. Tried this also: C:\Users\west\Downloads\bazel-0.4.3\bazel-0.4.3>bash ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as se
cond argument:
INFO:    ./compile.sh compile /path/to/bazel
▒▒▒▒  Building Bazel from scratchFile not found - *.jar
File not found - *.jar
no error prone jar

Please suggest how to resolve above issue or any other guided way to start using **wycheproof** for analyzing crypto libraries 

Best Regards,
Sunil

**Comment by thaidn** [comment]
It seems that you didn't get bazel installed successfully. bazel on Windows is highly experimental, please follow the instructions at https://bazel.build/versions/master/docs/install.html#windows and try again. I recommend downloading a precompiled binary.

Since this is not related to Wycheproof, I'm going to close this bug. Please reopen if if you still have trouble after installing bazel.
