### ISSUE TITLE
Installation with OS 

### ISSUE THREAD

**Issue by cheri3a** [google/wycheproof#13]
Installation and setup guide with debain ,CENTOS 
any installation guide or video available to setup wycheproof?

Best Regards,
cheri3a

**Comment by thaidn** [comment]
I'm sorry, but no installation guide. You can follow the instruction in https://github.com/google/wycheproof/blob/master/README.md to test Bouncy Castle or OpenJDK. Though I won't be surprised if most users just copy and use our tests as unit tests in their projects.

Please reopen this ticket if you have any other question.

**Comment by cheri3a** [comment]
thank's thaidn
