### ISSUE TITLE
BazelTestRunner exiting with a return value of 1

### ISSUE THREAD

**Issue by vincentcox-ordina** [google/wycheproof#15]
My system information:
`fresh Ubuntu 16.10` 
I have been following these commands:
```
$ sudo add-apt-repository ppa:webupd8team/java
$ sudo apt-get update
$ sudo apt-get install oracle-java8-installer
$ echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
$ curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
$ sudo apt-get update && sudo apt-get install bazel
$ sudo apt-get upgrade bazel
$ git clone https://github.com/google/wycheproof.git
$ cd wycheproof
```
fixed other errors (Java Security: Illegal key size or default parameters) by using https://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters

Now I still get some errors. The full output of the logfile can be found here: http://pastebin.com/hEQAbrDi
Any idea's?

**Comment by thaidn** [comment]
Thanks for trying it out!

> fixed other errors (Java Security: Illegal key size or default parameters) by using https://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters

This is in the README: https://github.com/google/wycheproof. There's a PR that fixes this issue without users having to download the policy files. Once it's merged, hopefully this problem will be resolved once and forever :).

> Now I still get some errors. The full output of the logfile can be found here: http://pastebin.com/hEQAbrDi

This is expected. The log file contains the failed tests -- there are 11 of them. I guess you were testing Bouncy Castle 1.55.

Please reopen this bug if you have any other question.
