### ISSUE TITLE
Repeated input values for primality test

### ISSUE THREAD

**Issue by randombit** [google/wycheproof#2]
I noticed some values are checked more than once by the primality test, and don't see any obvious reason for the test to repeat for just those inputs. The values 164280218643672633986221, 318665857834031151167461, and 360681321802296925566181 all appear multiple times in the test data in https://github.com/google/wycheproof/blob/master/java/com/google/security/wycheproof/testcases/BigIntegerTest.java

Maybe they can be removed, or maybe there should be a comment explaining the duplication.

Thanks for this great set of tests.

**Comment by thaidn** [comment]
Thanks randombit. We'll remove these dups soon.

**Comment by thaidn** [comment]
This is fixed with PR #19.
