### ISSUE TITLE
Copy-paste mistake in EcdhTest.java

### ISSUE THREAD

**Issue by internot** [google/wycheproof#23]
In https://github.com/google/wycheproof/blob/master/java/com/google/security/wycheproof/testcases/EcdhTest.java#L867 in method testDecode() there appears to be a copy-paste mistake:

`    ECParameterSpec params2 = key1.getParams(); // should be key2`

This makes the following asserts to always be true.

**Comment by thaidn** [comment]
Thanks. I'll send a PR.
