### ISSUE TITLE
Please make it possible to run tests on local jars

### ISSUE THREAD

**Issue by mouse07410** [google/wycheproof#4]
Current wycherproof tries to download BouncyCastle from the Internet. I need wycherproof to run tests on the local BouncyCastle jars.

How can I do it?

**Comment by thaidn** [comment]
Emilia, could you please take a look? Not urgent, but when you have cycles.

**Comment by mouse07410** [comment]
I think that far more people would like/need to test the stuff they have locally, compared to those who want to test what's in the global repo.

Thanks!

**Comment by peterdettman** [comment]
In the absence of an actual test target, you can at least edit the WORKSPACE file to configure a jar as a local file:

```
http_jar(
    name = "bouncycastle_1_56",
    url = "file:///Users/peter/Downloads/bcprov-jdk15on-156.jar"
)
```

You could just use an existing target and point its jar locally as above, or edit build_defs.bzl to add a separate target referencing the jar.

**Comment by Buantai** [comment]
Aw
aresome

**Comment by mouse07410** [comment]
I must be dense...

I've edited `WORKPSPACE` file (just removing the 1.48-1.54 related stuff at the top):
```
#maven_jar(
#    name = "bouncycastle_1_55",
#    artifact = "org.bouncycastle:bcprov-jdk15on:1.55",
#)

http_jar(
    name = "bouncycastle_1_56",
    url = "file:///Library/Java/Extensions/bcprov-ext-jdk15on-156.jar"
)
. . . . .
```

My attempt to do `bazel test BouncyCastleAllTests` produced:
```
$ bazel test BouncyCastleAllTests
Warning: ignoring http_proxy in environment.
..............
ERROR: /Users/ur20980/Src/wycheproof/BUILD:33:1: no such package '@bouncycastle_1_55//jar': error loading package 'external': The repository named 'bouncycastle_1_55' could not be resolved and referenced by '//:BouncyCastleAllTests'.
ERROR: Analysis of target '//:BouncyCastleAllTests' failed; build aborted.
INFO: Elapsed time: 4.864s
ERROR: Couldn't start the build. Unable to run tests.
$ 
```

Frankly, I am not aspiring to become a wycherproof wizard - being able to (smoothly) run it as a black box tool over my BouncyCastle jars (and later - over C++ crypto libraries like Crypto++) is all I hope for.

**Comment by mouse07410** [comment]
**Update2 - got something to run**

1. Did not remove the already-defined BouncyCastle targets - *added* `http_jar` for 1.56.
2. Edited `build_defs.bzl` changing in `bouncycastle_versions = range(49, 56)` "56" to "57" (yeah, obvious).
3. Ran `bazel test BouncyCastleTest_1_56`

And it failed:
```
$ bazel test BouncyCastleTest_1_56
Warning: ignoring http_proxy in environment.
INFO: Found 1 test target...
FAIL: //:BouncyCastleTest_1_56 (see /private/var/tmp/_bazel_uri/e4d57cbfa3d72fc2e017b4127feb30c0/execroot/wycheproof/bazel-out/local-fastbuild/testlogs/BouncyCastleTest_1_56/test.log).
Target //:BouncyCastleTest_1_56 up-to-date:
  bazel-bin/BouncyCastleTest_1_56.jar
  bazel-bin/BouncyCastleTest_1_56
INFO: Elapsed time: 21.920s, Critical Path: 16.34s
//:BouncyCastleTest_1_56                                                 FAILED in 14.1s
  /private/var/tmp/_bazel_uri/e4d57cbfa3d72fc2e017b4127feb30c0/execroot/wycheproof/bazel-out/local-fastbuild/testlogs/BouncyCastleTest_1_56/test.log

Executed 1 out of 1 test: 1 fails locally.
$ 
```

Here's the log:
[wycherproof-1.log.txt](https://github.com/google/wycheproof/files/674542/wycherproof-1.log.txt)

@peterdettman what's your take on this?

**Comment by peterdettman** [comment]
@mouse07410 Please see https://github.com/google/wycheproof/pull/8 for our proposed changes for BC 1.56, which addresses several of the failures (spurious ones I think). The remaining failures (after PR applied) are all related to CipherInputStream/CipherOutputStream behaviour with AEAD modes. I believe this is down to a disagreement over expected API behaviour (particularly when the MAC check fails).

**Comment by ekasper** [comment]
It's surprisingly non-trivial to supply a custom jar from the command line. I got something to work though it's fairly hackish - see https://github.com/google/wycheproof/pull/10

If we accept that users will have to edit the BUILD then we can trivially use bazel's [java_import](https://bazel.build/versions/master/docs/be/java.html#java_import) - but I'd rather they didn't have to touch the source.

**Comment by mouse07410** [comment]
> It's surprisingly non-trivial to supply a custom jar from the command line.......see #10

I can sympathize... And thank you for #10!

> If we accept that users will have to edit the BUILD then we can trivially use bazel's [java_import](https://bazel.build/versions/master/docs/be/java.html#java_import) - but I'd rather they didn't have to touch the source.

I agree. But I suspect that 99.99% of the entire population couldn't care less about how well BouncyCastle-1.49 behaves under test (and those people who *have* to use it, don't have any choice anyway - so why feed them correct but useless data?). I'd expect the majority to want to know how the current Github master holds up (granted, they'd need to be able to sign JCE provider), and how the latest-stable release does under test... From that point of view, I consider most of the `BUILD` to be of rather limited use.

So your #10 solution (or maybe a perfection/improvement of it) seems like the best way forward, IMHO.

**Comment by thaidn** [comment]
Thanks ekasper! mouse07410 please see if you can test your local jars now and reopen this ticket if you can't.

**Comment by mouse07410** [comment]
Yes, I can run the tests on the local JAR now - **thank you**!

**Comment by thaidn** [comment]
One problem is now bazel build ... stops working. I got this error

no such target '@local//:bouncycastle_jar': target 'bouncycastle_jar ' not declared in package '' defined by BUILD and referenced by '//:BouncyCastleTestLocal'.

**Comment by ekasper** [comment]
Can you try adding `tags=["manual"]` to the local rules?

> Targets with tags=["manual"] will not be included in wildcard target patterns (..., :*, :all, etc). You should specify such test targets with explicit target patterns on the command line if you want Bazel to build/test them.

https://bazel.build/versions/master/docs/bazel-user-manual.html#target-patterns
