### ISSUE TITLE
ECDSA test vectors and docs

### ISSUE THREAD

**Issue by loriochi** [google/wycheproof#46]
ECDSA tests implemented so far do not cover different combinations of standard elliptic curves with hash functions. In particular, the code we would like to test uses SHA-384 with secp384r1. 
There is also no documentation regarding how these test vectors were created and what sources were used.

**Comment by bleichen** [comment]
I'm just wondering what combinations are actually used. The current plan is to precompute
test vectors for
	
ecdsa_brainpoolP224r1_sha224
ecdsa_brainpoolP256r1_sha256
ecdsa_brainpoolP320r1_sha384
ecdsa_brainpoolP384r1_sha384
ecdsa_brainpoolP512r1_sha512
ecdsa_secp224r1_sha224
ecdsa_secp224r1_sha256
ecdsa_secp256k1_sha256
ecdsa_secp256r1_sha256
ecdsa_secp384r1_sha384
ecdsa_secp384r1_sha512
ecdsa_secp521r1_sha512
as well as
eddsa over edwards25519

**Comment by thaidn** [comment]
This is done. Please see the test vectors in https://github.com/google/wycheproof/tree/master/testvectors.
