### ISSUE TITLE
Readme Link Wrong

### ISSUE THREAD

**Issue by StuartWinterTear** [google/wycheproof#49]
The Readme link:

"For more information on the goals and strategies of Project Wycheproof, please check out our doc."

"Doc" hyperlink Is 404.

https://github.com/google/wycheproof/blob/master/g3doc

Needs changing.

Thanks

**Comment by StuartWinterTear** [comment]
Actually I think it's all the Github internal links noted in the Readme.

**Comment by thaidn** [comment]
Thanks. I'm fixing it.

**Comment by StuartWinterTear** [comment]
You're a star. Thanks.

**Comment by thaidn** [comment]
This is fixed in https://github.com/google/wycheproof/commit/16b1d26f28280de2479cc5f0595f936088c515fe.

Thanks for reporting it!
