### ISSUE TITLE
logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [google/wycheproof#51]
Hi, I've designed a logo for the project. If you liked it i will send you the files. 

logo
![wycheproof-01-01](https://user-images.githubusercontent.com/36028424/38450163-dbc00ca6-3a4b-11e8-9ea2-4d1da240b733.png)

logotype 1
![wycheproof-02](https://user-images.githubusercontent.com/36028424/38450096-fb53b122-3a4a-11e8-8ba7-f3d225c2793b.png)

logotype 2
![wycheproof-03](https://user-images.githubusercontent.com/36028424/38450109-0fd5fa9c-3a4b-11e8-89e1-f4cc82836db2.png)

Best regards,
Tobaloidee

**Comment by hemangshah** [comment]
@Tobaloidee, you have open this issue in a Google's project. So they have contribution guidelines which one needs to follow. Have a look and contribute in that way! Hope to see your logo will accept by the Google team. https://github.com/google/wycheproof/blob/master/CONTRIBUTING.md
