### ISSUE TITLE
rsa_signature_tests.json uses 1024-bit keys for all tests

### ISSUE THREAD

**Issue by briansmith** [google/wycheproof#54]
If the implementation properly rejects all small RSA keys then rsa_signature_tests.json is useless: all negative test vectors will pass since the key will be rejected for being too small, and both positive test vectors will fail for the same reason.

In the case of [*ring*](https://github.com/briansmith/ring), 2048-bit keys are the minimum size accepted and I expect this to become more common.

**Comment by thaidn** [comment]
@bleichen 

This looks like something that we should fix.

**Comment by bleichen** [comment]
Thanks. I'm fixing this. 
Each key size is getting its own JSON file, so that implementations can ignore the sizes that are not supported.

**Comment by thaidn** [comment]
I think this is fixed. Brian, could you please try again and reopen this ticket if it still doesn't work for you?
