### ISSUE TITLE
X448 vectors?

### ISSUE THREAD

**Issue by alex** [google/wycheproof#64]
Are there any plans to introduce test vectors for x448?

**Comment by bleichen** [comment]
Yes. Some test vectors will be added in the next release. I've also generated separate test vector files for X25519 and X448 using ASN encoding for the keys. This makes it easier to use the test vectors with JCE.

**Comment by reaperhulk** [comment]
Terrific! ed448 would also be very useful if possible.

**Comment by bleichen** [comment]
The next version 0.6, which is waiting for release adds test vectors for RSA-OAEP,  ECDSA with P1363 encoding, XDH (X448 and ASN encoded keys).

Ed448 will be added in version 0.7, together with other schemes using SHA-3. I'm also working on JSON schemas for the test vectors and documentation.

**Comment by alex** [comment]
👍  for Ed448 we ended up building our own test to find a signature malleability issue in OpenSSL: https://github.com/openssl/openssl/issues/7706

**Comment by thaidn** [comment]
Ed448 test vectors can be found here: https://github.com/google/wycheproof/blob/master/testvectors/ed448_test.json.
